== Input parameters

[width="100%",cols="7%,1%,25%a,1%,20%,50%a",options="header",]
|===
|Name |Type |Default value |Required |Steps |Description
|AWS_ACCESS_KEY_ID |string |unset |yes |plan, apply, plan-destroy, destroy
|AWS access key id

|AWS_SECRET_ACCESS_KEY |string |unset |yes |plan, apply, plan-destroy, destroy
|AWS access key secret

|M_NAT_GATEWAY_COUNT |number |1 |no |init |The number of NAT gateways
to be created. Attached into subnets with round-robin. Public and private subnets must be created in order to use NAT Gateway.

|M_SUBNETS |list(map)
|
[source]
----
{
  private:
  [{
    name: first_private_subnet,
    availability_zone: any,
    address_prefixes: 10.1.1.0/24
  }],
  public:
  [{
    name: first_public_subnet,
    availability_zone: any,
    address_prefixes: 10.1.2.0/24
  }]
}
----
|no |init |Defines public and private subnets
that are created in specified or any available AZs

|M_VM_GROUPS |list(map)
|
[source]
----
{
  name: vm-group0,
  vm_count: 1,
  vm_size: "t3.medium",
  use_public_ip: false,
  subnet_names: ["first_private_subnet"],
  sg_names: ["default_sg"],
  vm_image: {
    ami: "RHEL-7.8_HVM_GA-20200225-x86_64-1-Hourly2-GP2", # In case of Ubuntu: "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20200611"
    owner: "309956199498", # In case of Ubuntu: "099720109477"
  },
  data_disks: [
    {
      device_name: "/dev/sdf", #/dev/sd[f-p]
      disk_size_gb: 16,
      type: "gp2"
    }
  ]
}
----
|no |init |Defines vm groups with specified parameters. In order to use public IP, public subnet must be created and used by vm group. :warning:
Possible to create VPC with a single public subnet, VPC with public and private subnets (NAT), VPC with public and private subnets (without NAT) or VPC with only private subnets.

|M_SECURITY_GROUPS |map
|
[source]
----
[
  {
    name: default_sg,
    rules: {
      ingress: [
        {
          protocol: "-1",
          from_port: 0,
          to_port: 0,
          cidr_blocks: ["10.1.0.0/20"]
        },
        {
          protocol: "tcp",
          from_port: 22,
          to_port: 22,
          cidr_blocks: ["0.0.0.0/0"]
        }
      ],
      egress: [
      	{
          protocol: "-1",
          from_port: 0,
          to_port: 0,
          cidr_blocks: ["0.0.0.0/0"]
        }
      ]
    }
  }
]
----
|no |init |Defines the list of security groups to attach virtual machines to

|M_NAME |string |epiphany |no |init |Name to be used on all resources
as a prefix

|M_VMS_RSA |string |vms_rsa |no |init |SSH key name, should be located in
shared directory

|M_REGION |string |eu-central-1 |no |init |AWS Region to launch
module in

|M_ADDRESS_SPACE |string |10.1.0.0/20 |no |init |VPC address space

|===
