== Input parameters

[width="100%",cols="7%,1%,25%a,1%,20%,50%a",options="header",]
|===
|Name |Type |Default value |Required |Steps |Description
|AWS_ACCESS_KEY_ID |string |unset |yes |plan, apply, plan-destroy, destroy
|AWS access key id

|AWS_SECRET_ACCESS_KEY |string |unset |yes |plan, apply, plan-destroy, destroy
|AWS access key secret

|M_VMS_COUNT |number |1 |no |init |Number of instances to launch

|M_PUBLIC_IPS |bool |false |no |init |If true, the EC2 instance
will have associated public IP address

|M_NAT_GATEWAY_COUNT |number |1 |no |init |The number of NAT gateways
to be created. Attached into subnets with round-robin

|M_SUBNETS |list(map)
|
[source]
----
{
  private:
  [{
    name: first_private_subnet,
    availability_zone: any,
    address_prefixes: 10.1.1.0/24
  }],
  public:
  [{
    name: first_public_subnet,
    availability_zone: any,
    address_prefixes: 10.1.2.0/24
  }]
}
----
|no |init |Defines public and private subnets
that are created in specified or any available AZs

|M_SECURITY_GROUPS |map
|
[source]
----
[
  {
    name: default_sg,
    rules: {
      ingress: [
        {
          protocol: "-1",
          from_port: 0,
          to_port: 0,
          cidr_blocks: ["0.0.0.0/0"]
        }
      ],
      egress: [
      	{
          protocol: "-1",
          from_port: 0,
          to_port: 0,
          cidr_blocks: ["0.0.0.0/0"]
        }
      ]
    }
  }
]
----
|no |init |Defines the list of security groups to attach virtual machines to

|M_NAME |string |epiphany |no |init |Name to be used on all resources
as a prefix

|M_VMS_RSA |string |vms_rsa |no |init |SSH key name, should be located in
shared directory

|M_REGION |string |eu-central-1 |no |init |AWS Region to launch
module in

|M_ADDRESS_SPACE |string |10.1.0.0/20 |no |init |VPC address space

|M_OS |string |ubuntu |no |init |Operating System to launch.
Possible values: ubuntu/redhat
|===
